"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
exports.default = RootLayout;
const google_1 = require("next/font/google");
require("./globals.css");
const layout_module_css_1 = __importDefault(require("./layout.module.css"));
const inter = (0, google_1.Inter)({ subsets: ["latin"] });
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout({ children, }) {
    return (<html lang="en">
      <body className={inter.className}>
        <main className={layout_module_css_1.default.main}>{children}</main>
      </body>
    </html>);
}
